export {
  ScB2bError,
  clearScB2bToken,
  isScB2bConfigured,
  scB2bConfig,
  scB2bDownload,
  scB2bGet,
  scB2bLoginProbe,
  scB2bPost,
  withQuery,
  type ScB2bBinary,
  type ScB2bConfig,
} from "./client";

export {
  agriQuoteAndIssue,
  buildCa7Quote,
  buildCp7Quote,
  issueAtm,
  issueCa7,
  issueCp7,
  quoteAtm,
  quoteCa7,
  quoteCp7,
  quoteLife,
  type Ca7QuoteInput,
  type Cp7QuoteInput,
} from "./quotes";

export {
  REPORT_PATHS,
  agriCatalog,
  agriQuoteResult,
  argentineProvinces,
  citiesByPostalCode,
  claimByNumber,
  claimsByProducer,
  claimsNews,
  cuilsByDni,
  currentProducers,
  downloadReport,
  earnedCommissions,
  jobMovements,
  monthPeriod,
  currentYearMonth,
  movementQueryDate,
  motoVersion,
  paymentHistory,
  policyByNumber,
  policyDetailByProduct,
  producerAffinity,
  producerCode,
  producerInfo,
  producerMovements,
  producerPortfolio,
  previousDayIso,
  SC_AUTO_POLICY_TYPE,
  SC_AUTO_PRODUCT,
  searchPolicy,
  taxIdFromProducerPayload,
  typeList,
  vehicleByPlate,
  vehicleVersion,
  type AgriCatalogKind,
  type ReportKind,
} from "./ops";
